apps/servicios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

from apps.servicios.forms import PlatilloSearchForm
from apps.servicios.views import basic_search_nanoz

urlpatterns = [
    url(r'perfil-restaurante/(?P<slug>[\w-]+)/', 'apps.servicios.views.perfilRestaurante', name='perfilRestaurante'),
    url(r'mis-restaurantes/', 'apps.servicios.views.VistaRestaurante', name='verRestaurantes'),
    url(r'restaurante/(?P<slugRestaurante>[\w-]+)/platillo/(?P<slugPlatillo>[\w-]+)/$',
        'apps.servicios.views.detallePlatillo', name='detallePlatillo'),
    url(r'actualizar-platillo/', 'apps.servicios.views.ModificarPlatillo', name='actualizarPlatillo'),
    url(r'cancelar-pedido/', 'apps.servicios.views.cancelar_pedido', name='cancelarPedido'),
    url(r'actualizar-pedido/', 'apps.servicios.views.actualizar_pedido', name='actualizarPedido'),
    url(r'ajaxAgregarFavoritos/$', 'apps.servicios.views.ajaxAgregarFavoritos', name='ajaxAgregarFavoritos'),
    url(r'ajaxAgregarFavoritos2/$', 'apps.servicios.views.ajaxAgregarFavoritos2', name='ajaxAgregarFavoritos2'),
    url(r'ajax_agregar_platillo/$', 'apps.servicios.views.ajaxAgregarPlatillo', name='ajaxAgregarPlatillo'),
    url(r'ajax_quitar_platillo/$', 'apps.servicios.views.ajaxQuitarPlatillo', name='ajaxQuitarPlatillo'),
    url(r'ajax_quitar_1_platillo/$', 'apps.servicios.views.ajaxQuitar1Platillo', name='ajaxQuitar1Platillo'),
    # url(r'^search/', include('haystack.urls')),
    # url(r'^buscador/?$', MySearchView.as_view(), name="buscador"),
    # url(r'^buscador2/?$', buscador2, name="buscador2"),
    url(r'ajaxObtenerSemana/$', 'apps.servicios.views.ajaxObtenerSemana', name='ajaxObtenerSemana'),
    url(r'ajaxObtenerSemanaFacturas/$', 'apps.servicios.views.ajaxObtenerSemanaFacturas',
        name='ajaxObtenerSemanaFacturas'),
    url(r'ajaxObtenerExpecificacionSemana/$', 'apps.servicios.views.ajaxObtenerExpecificacionSemana',
        name='ajaxObtenerExpecificacionSemana'),
    url(r'^ordenar/?$', 'apps.servicios.views.search_with_form', name="buscador2"),
    url(r'^buscadorV2/?$', basic_search_nanoz, {
        'load_all': False,
        "form_class": PlatilloSearchForm,
    }, name="buscador"),

]

apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.usuarios.views.usuarioPerfil', name='usuarioPerfil'),
    url(r'login/$', 'apps.usuarios.views.LogIn', name='LogIn'),
    url(r'logout/$', 'apps.usuarios.views.LogOut', name='LogOut'),
    url(r'preguntas-frecuentes/$', 'apps.usuarios.views.faq', name='faq'),
    url(r'condiciones/$', 'apps.usuarios.views.condiciones', name='condiciones'),
    url(r'perfil/$', 'apps.servicios.views.PerfilUsuario', name='Perfil'),
    url(r'ajax_validar_correo/$', 'apps.usuarios.views.ajax_validar_correo', name='ajax_validar_correo'),
    url(r'ajax_actualizar_pedidos/$', 'apps.usuarios.views.ajax_actualizar_pedidos', name='ajax_actualizar_pedidos'),
    url(r'contacto/$', 'apps.usuarios.views.contactoRestaurante', name='Contacto'),
    url(r'mis-datos/$', 'apps.usuarios.views.datosExtra', name='datosExtra'),
    url(r'restaurante-datos/(?P<llave>\w+)/$', 'apps.usuarios.views.agregarRestaurante', name='addRestaurante'),
    url(r'restaurante/(?P<slug>[\w-]+)/$', 'apps.usuarios.views.detalleRestaurante', name='detalleRestaurante'),
    url(r'control-restaurantes/$', 'apps.usuarios.views.testGlovalV2', name='controlRestaurantes'),
    url(r'test/$', 'apps.usuarios.views.testGlovalV2', name='test'),
]

deliandgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [
    url(r'^$', 'apps.servicios.views.VistaPlatillos', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.estadisticas.urls', namespace='estadisticas_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.catalogos.urls', namespace='catalogos_app')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    # urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/estadisticas/models.py
# -*- encoding: utf-8 -*-
from django.db import models

from apps.catalogos.models import Pregunta
from apps.servicios.models import Platillo
from apps.usuarios.models import Restaurante, Usuario

#todo: si un comentario tiene como usuario=0 es por que fue extraido desde yelp!
class Comentarios(models.Model):
    restaurante = models.ForeignKey(Restaurante)
    usuario = models.IntegerField(default=0)
    nombre = models.CharField(max_length=100)
    fecha = models.DateTimeField(auto_now_add=True)
    CALIFICAIONES = ((5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'),)
    valoracion = models.IntegerField(choices=CALIFICAIONES, null=True)
    texto = models.TextField()
    visible = models.BooleanField(default=True)

    def __unicode__(self):
        return ""

    def __str__(self):
        return ""

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"


class Metadatos(models.Model):
    ip = models.CharField(max_length=20)
    usuario = models.IntegerField(default=0)
    dia_hora = models.DateTimeField(auto_now_add=True)
    pagina_visitada = models.URLField()
    proyecto = models.IntegerField(default=0)
    sistema_operativo = models.CharField(max_length=100)
    navegador = models.CharField(max_length=30)
    pagina_procedencia = models.URLField()
    dispositivo = models.CharField(max_length=20)

    def __str__(self):
        if self.usuario != 0:
            try:
                return Usuario.objects.get(id=self.usuario).username
            except:
                return 'anonimo'
        else:
            return 'Anonimo'

    def __unicode__(self):
        if self.usuario != 0:
            try:
                return Usuario.objects.get(id=self.usuario).username
            except:
                return 'anonimo'
        else:
            return 'Anonimo'

    @property
    def username(self):
        if self.usuario != 0:
            try:
                return Usuario.objects.get(id=self.usuario).username
            except:
                return 'anonimo'
        else:
            return 'Anonimo'


class Respuesta(models.Model):
    pregunta = models.ForeignKey(Pregunta)
    respuesta = models.CharField(max_length=300)


class TestNecesidad(models.Model):
    usuario = models.ForeignKey(Usuario)
    respuesta = models.ManyToManyField(Respuesta)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "cuestionario de " + self.usuario

    def __unicode__(self):
        return "cuestionario de " + self.usuario


class RestauranteFavoritos(models.Model):
    usuario = models.ForeignKey(Usuario)
    restaurante = models.ForeignKey(Restaurante)

    def __str__(self):
        return str(self.restaurante.get_name) + " - " + str(self.usuario.nombre)

    def __unicode__(self):
        return str(self.restaurante.get_name) + " - " + str(self.usuario.nombre)


class PlatilloFavoritos(models.Model):
    usuario = models.ForeignKey(Usuario)
    platillo = models.ForeignKey(Platillo)

    def __str__(self):
        return str(self.platillo.nombre) + " - " + str(self.usuario.nombre)

    def __unicode__(self):
        return str(self.platillo.nombre) + " - " + str(self.usuario.nombre)

apps/servicios/views.py
# -*- encoding: utf-8 -*-
import json
import math
from datetime import time, date

from carton.cart import Cart
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import InvalidPage, Paginator
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from haystack.forms import ModelSearchForm
from haystack.generic_views import SearchView
from haystack.query import EmptySearchQuerySet
from haystack.query import SearchQuerySet

from apps.catalogos.models import Tags
from apps.estadisticas.models import RestauranteFavoritos, PlatilloFavoritos
from apps.servicios.forms import PlatilloForm, PlatilloUpdateForm, PlatilloSearchForm, PlatilloSearchFormV2, \
    FavoritosForm, BancoForm
from apps.servicios.functions import lista_restaurantes_semana, listar_movimientos_restaurante_semana, \
    dame_semanas_disponiblesv2
from apps.servicios.models import Platillo, ControlNutrimental, Pedido, Favoritos, Facturas
from apps.usuarios.forms import updateInfoRestauranteForm, updateImagenRestauranteForm, updateImagenPlatilloForm, \
    updateUsuarioForm, updateImgUsuarioForm
from apps.usuarios.mailing import correo05
from apps.usuarios.models import Restaurante, Contacto, Usuario

RESULTS_PER_PAGE = getattr(settings, 'HAYSTACK_SEARCH_RESULTS_PER_PAGE', 20)


@login_required
def perfilRestaurante(request, slug):
    print("entrando ala vista de platillos")
    print(slug)
    print("GET")
    print(request.GET)
    print("POST")
    print(request.POST)
    print("FILES")
    print(request.FILES)
    restaurantes = Restaurante.objects.filter(slug=slug, duenio=request.user)
    print(restaurantes)
    if restaurantes.exists():
        print("el restaurante si existe")
        restaurante = restaurantes.first()
        if request.method == "POST":
            formPlatillo = PlatilloForm(request.POST, request.FILES)
            formRestaurante = updateInfoRestauranteForm(request.POST, request.FILES)
            formImgRestaurante = updateImagenRestauranteForm(request.POST, request.FILES)
            formImgPlatillo = updateImagenPlatilloForm(request.POST, request.FILES)
            formBanco = BancoForm(request.POST)
            print(formPlatillo.is_valid())
            print(formRestaurante.is_valid())
            print(formImgRestaurante.is_valid())
            print(formImgPlatillo.is_valid())
            print(formBanco.is_valid())
            if formBanco.is_valid():
                banco = formBanco.save()
                restaurante.cuenta_bancaria = banco
                restaurante.save()
            if formPlatillo.is_valid():
                try:
                    nuevoPlatillo = formPlatillo.save(commit=False)
                    nuevoPlatillo.restaurante = restaurante
                    nuevoPlatillo.save()
                    lista = []
                    for id in request.POST.getlist('tags'):
                        lista.append(int(id))
                    try:
                        nuevoPlatillo.tags = Tags.objects.filter(id__in=lista)
                    except Exception as e:
                        print("Erro al guardar los tags")
                        print(e.args)
                    lista = []
                    if 'control' in request.POST:
                        for id in request.POST.getlist('control'):
                            lista.append(int(id))
                    try:
                        control = ControlNutrimental.objects.filter(id__in=lista)
                        nuevoPlatillo.control_nutrimental = control
                    except Exception as e:
                        print("Error al guardar los tags")
                        print(e.args)
                    nuevoPlatillo.save()
                    return redirect(reverse('servicios_app:perfilRestaurante', kwargs={
                        'slug': restaurante.slug
                    }))
                except Exception as e:
                    print(e)
            if formRestaurante.is_valid():
                restaurante.servicio = request.POST["servicio"]
                restaurante.alcanze = request.POST["alcanze"]
                restaurante.tags = Tags.objects.filter(id__in=request.POST.getlist("tags"))
                restaurante.compra_minima = request.POST["compra_minima"]
                restaurante.costo_envio = request.POST["costo_envio"]
                try:
                    if "hora_abre" in request.POST:
                        hora = str(request.POST["hora_abre"]).split(":")
                        restaurante.hora_abre = time(int(hora[0]), int(hora[1]), int(hora[2]))
                    if "hora_cierra" in request.POST:
                        hora = str(request.POST["hora_cierra"]).split(":")
                        restaurante.hora_cierra = time(int(hora[0]), int(hora[1]), int(hora[2]))
                except:
                    pass
                restaurante.save()
                contacto = Contacto.objects.get(id=restaurante.contacto.id)
                contacto.email = request.POST["email"]
                contacto.telefono = request.POST["telefono"]
                contacto.nombre_restaurante = request.POST["nombre_restaurante"]

            if formImgRestaurante.is_valid():
                restaurante.imagen = request.FILES["imagen"]
                restaurante.save()
            if formImgPlatillo.is_valid():
                platilloTemp = Platillo.objects.get(id=request.POST["id_platillo"], restaurante=restaurante)
                platilloTemp.imagen = request.FILES["imagen"]
                platilloTemp.save()
        platillos = Platillo.objects.filter(restaurante=restaurante)
        print(platillos)
        pedidos = Pedido.objects.filter(platillo__restaurante=restaurante).exclude(estado="en cargo").distinct()
        semanas = dame_semanas_disponiblesv2(restaurante)
        data = {
            "nombre": restaurante.contacto.nombre_responsable,
            "telefono": restaurante.contacto.telefono,
            "email": restaurante.contacto.email,
            "compra_minima": restaurante.compra_minima,
            "alcanze": restaurante.alcanze,
            "hora_cierra": restaurante.hora_cierra,
            "hora_abre": restaurante.hora_abre,
            "costo_envio": restaurante.costo_envio,
        }
        formRestaurante = updateInfoRestauranteForm(data=data)
        formImgRestaurante = updateImagenRestauranteForm(data={
            "slug": slug,
        })
        formPlatillo = PlatilloForm()
        for platillo in platillos:
            platillo.formUpdateInfo = PlatilloUpdateForm(instance=platillo)
            platillo.formUpdateImg = updateImagenPlatilloForm(data={
                "id_platillo": platillo.id,
            })
        formBanco = BancoForm()
        return render(request, "servicios/perfilRestaurante.html", {
            "form_platillo": formPlatillo,
            "form_restaurante": formRestaurante,
            "form_imgRestaurante": formImgRestaurante,
            "slug": slug,
            "restaurante": restaurante,
            "platillos": platillos,
            "pedidos": pedidos,
            "semanas": semanas,
            "form_Banco": formBanco,

        })
    else:
        print("no se encontro ningun restaurante se le enviara al home")
        return redirect(reverse('index'))


def VistaPlatillos(request):
    Platillos = Platillo.objects.all()
    return render(request, "servicios/VistaPlatillos.html", {
        "platillos": Platillos
    })


@login_required
def VistaRestaurante(request):
    user = request.user
    if user.is_restaurante:
        restaurantes = Restaurante.objects.filter(duenio=user)
        if restaurantes.exists():
            return render(request, "servicios/listaRestaurantes.html", {
                "restaurantes": restaurantes
            })
    return redirect(reverse('index'))


@login_required
def ModificarPlatillo(request):
    print("get")
    print(request.GET)
    print("post")
    print(request.POST)
    print("files")
    print(request.FILES)
    print("fin de request")
    if request.method == "POST":
        if "slug" in request.POST:
            try:
                restaurante = Restaurante.objects.get(slug=request.POST["slug"])
                platillo = Platillo.objects.get(id=request.POST["id"])
                platillo.descripcion = request.POST["descripcion"]
                platillo.control_nutrimental = request.POST.getlist("control")
                platillo.tags = request.POST.getlist("tags")
                platillo.nombre = request.POST["nombre"]
                try:
                    if "hora_inicia" in request.POST:
                        hora = str(request.POST["hora_inicia"]).split(":")
                        platillo.hora_inicia = time(int(hora[0]), int(hora[1]), int(hora[2]))
                    if "hora_final" in request.POST:
                        hora = str(request.POST["hora_final"]).split(":")
                        platillo.hora_final = time(int(hora[0]), int(hora[1]), int(hora[2]))
                    platillo.tiempo_preparacion = int(float(request.POST["tiempo_preparacion"]))
                except:
                    pass
                platillo.save()
                return redirect(reverse('servicios_app:perfilRestaurante', kwargs={
                    'slug': restaurante.slug
                }))
            except:
                pass
    return redirect(reverse('index'))


@login_required
def PerfilUsuario(request):
    print("GET")
    print(request.GET)
    print("POST")
    print(request.POST)
    print("FILES")
    print(request.FILES)
    print("fin del request")
    usuario = Usuario.objects.get(id=request.user.id)
    estilos = Tags.objects.all()

templates/servicios/VistaPlatillos.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}
    Elige tus platillos | Deli&Go
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row section">
            {% for platillo in platillos %}
                <div class="col-lg-4">
                    {% include 'base/base_platillo_card.html' %}
                </div>
                {% comment %}
                <div class="col-lg-3">
                    <form action="{% url 'servicios_app:detallePlatillo' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id_platillo" value="{{ platillo.id }}">
                        <input type="image" src="{{ platillo.imagen.url }}" height="250" width="250">
                    </form>
                </div>

                {% if forloop.counter|divisibleby:2 %}
                    </div>
                    <div class="row">
                {% endif %}
                {% endcomment %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        function ajaxAgregarPlatillo(id_platillo) {
            console.log(id_platillo);
            $.ajax({
                url: "{% url 'servicios_app:ajaxAgregarPlatillo' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {

                },
                success: function (data) {
                    detar
                },
                error: function (xhr, errmsg, err) {
                    alert("no se pudo agregar el platillo")
                }
            });
        }
    </script>
{% endblock %}

templates/servicios/detallePlatillo.html
{% extends 'base/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block title %}
    Detalle platilllo | Deli&Go
{% endblock %}


{% block styles %}

    <link rel="stylesheet" href="{% static 'base/css/stars.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/starability/starability-minified/starability-all.min.css' %}">

    <style>

        .starability-basic label:before, label:after {
            display: none;
        }

        .starability-basic [type="radio"] + label {
            padding-left: 0 !important;
            height: 30px !important;
        }

        .starability-basic.sm {
            width: 75px;
            min-height: inherit;
        }

        .starability-basic.sm > label {
            width: 15px;
            height: 15px;
            background-size: 15px;
        }

        .starability-basic.sm > input:checked ~ label, .starability-basic.sm > input:focus ~ label, .starability-basic.sm > input:hover ~ label {
            background-position: 0 -15px;
        }


    </style>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row section">
            <div class="col-md-7">
                <div id="imagen-platillo" class="border">
                    <style>
                        #imagen-platillo {
                            background: url({{ platillo.imagen.url }}) center center;
                            background-size: cover;
                            padding-bottom: 56%;
                        }
                    </style>
                </div>
                <div class="white p-xxs border mt--xxs">
                    <h6 class="font-600 mt--xs mb-0">
                        <a href="{% url 'usuarios_app:detalleRestaurante' platillo.restaurante.slug %}">
                            <div id="imagen-restaurante" class="inline border">
                                <style>
                                    #imagen-restaurante {
                                        height: 2.8em;
                                        width: 2.8em;
                                        background: url({{ platillo.restaurante.urlImagen }}) center center;
                                        background-size: cover;
                                        border-radius: 50%;
                                        top: 1em;
                                        position: relative;
                                        content: '';
                                    }
                                </style>
                            </div>
                            <span class="inline font-800">
                                &nbsp;&nbsp;{{ platillo.restaurante.contacto.nombre_restaurante }}
                            </span>
                            <br>
                            <div class="stars-container inline" style="top: 6px; left: 50px;">
                                <div class="stars-top"
                                     style="width: {% widthratio platillo.restaurante.comentarioAvg 5 100 %}%;">
                                    <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                </div>
                                <div class="stars-bottom">
                                    <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                </div>
                            </div>
                        </a>
                    </h6>
                </div>
            </div>
            <div class="col-md-5">
                <h3 class="m-t-m mb-xxs">
                    <b>{{ platillo.nombre }}</b>
                </h3>
                <div>
                    {% for tag in platillo.tags.all %}
                        <span class="label label-tag">{{ tag }}</span>
                    {% endfor %}
                </div>
                <h6>
                    <i class="ion-android-time"></i>&nbsp;{{ platillo.tiempo_preparacion }} minutos.
                    &nbsp;&nbsp;
                    <span class="text-muted">
                        <i class="ion-ios-calendar-outline"></i>&nbsp;
                        Disponible:
                        {{ platillo.hora_inicia|time:"h:i A" }} - {{ platillo.hora_final|time:"h:i A" }}
                    </span>
                </h6>

                <p class="text-black text-justify">
                    {{ platillo.descripcion }}
                </p>
                <div class="row">
                    {% for control in platillo.control_nutrimental.all %}
                        <div class="col-xs-6">
                            <li class="text-default">{{ control }}</li>
                        </div>
                    {% endfor %}
                </div>
                <div class="row mt-xs">
                    <div class="col-xs-6">
                        <h4 class="text-primary font-600 left m-t-sm">
                            <i class="ion-social-usd"></i>&nbsp;{{ platillo.precio|floatformat:'2' }}
                        </h4>
                    </div>
                    <div class="col-xs-6">
                        <button class="btn btn-lg btn-warning no-shadow right"
                                onclick="ajaxAgregarPlatillo({{ platillo.id|floatformat:'0' }})">
                            <i class="ion-bag"></i>&nbsp;&nbsp;Agregar a pedido
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="text-center">
        <hr>
        <h4 class="font-800 mt-l">
            Sugerencias de
            <a href="{% url 'usuarios_app:detalleRestaurante' platillo.restaurante.slug %}">
                {{ platillo.restaurante.contacto.nombre_restaurante }}
            </a>
        </h4>
    </div>
    <div class="container">
        <div class="row section">
            {% for platillo in otrosPlatillos %}
                <div class="col-md-3">
                    {% include 'base/base_platillo_card.html' %}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="white border-top">
        <div class="container">
            <div class="row section">
                <div class="col-xs-12">
                    <h4 class="font-800 text-center">
                        Comentarios ({{ platillo.restaurante.comentarios_set.count }})
                    </h4>

                    <div class="row section">
                        {% if not platillo.restaurante.comentarios_set.count %}
                            <p>No hay comentarios aún</p>
                        {% else %}
                            {% for comentario in platillo.restaurante.comentarios_set.all %}
                                <div class="col-md-6">
                                    <div class="row p-sm m-t-none m-b-none b-b">
                                        <div class="col col-sm-2">
                                            <div class="circle responsive-img center-block avatar-sm m-t-xs"
                                                 id="comentario{{ comentario.id }}">
                                                <style>
                                                    #comentario{{ comentario.id }} {
                                                        background: url({{ user.get_image_url }}) center center;
                                                        width: 50px;
                                                        height: 50px;
                                                        border-radius: 50%;
                                                        background-size: cover;
                                                    }
                                                </style>
                                            </div>
                                        </div>
                                        <div class="col col-sm-10">
                                            <b class="comentario-nombre">{{ comentario.usuario.get_short_name }}</b>
                                            <p class="comentario-texto grey-text mb-0 mt-xxxs">{{ comentario.texto }}</p>
                                            <div class="stars-container inline" style="top: -6px;">
                                                <div class="stars-top"
                                                     style="width: {% widthratio comentario.valoracion 5 100 %}%;">
                                                    <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                                </div>
                                                <div class="stars-bottom">
                                                    <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                                </div>
                                            </div>
                                            <div class="comentario-fecha grey-text inline ml-xs"
                                                 style="top: -8px; position: relative;">
                                                <small>{{ comentario.fecha|naturaltime }}</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        function ajaxAgregarPlatillo(id_platillo) {
            $.ajax({
                url: "{% url 'servicios_app:ajaxAgregarPlatillo' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function () {

                },
                success: function () {
                    $.notify({
                        // options
                        message: 'Se ha agregado el platillo a tu pedido'
                    }, {
                        // settings
                        type: 'danger',
                        delay: 500
                    });
                },
                error: function (xhr, errmsg, err) {
                    alert("no se pudo agregar el platillo")
                }
            });
        }
        function ajaxAgregarFavoritos(id_platillo) {
            $.ajax({
                url: "{% url 'servicios_app:ajaxAgregarFavoritos2' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {

                },
                success: function (data) {
                    alert("Platillo Agregado a Favoritos")
                },
                error: function (xhr, errmsg, err) {
                    alert("No puedes tener 2 veces el mismo Platillo en favoritos")
                }
            });
        }
        function ajaxAgregarFavoritos2(id_platillo) {
            $.ajax({
                url: "{% url 'servicios_app:ajaxAgregarFavoritos2' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {

                },
                success: function (data) {
                    alert("Platillo Agregado a Favoritos")
                },
                error: function (xhr, errmsg, err) {
                    alert("No puedes tener 2 veces el mismo Platillo en favoritos")
                }
            });
        }
    </script>
{% endblock %}