apps/pagos/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    url(r'^carrito/$', 'apps.pagos.views.VerCarrito', name='VerCarrito'),
    # url(r'^preOrden/$', 'apps.pagos.views.preOrden', name='preOrden'),
    url(r'^preOrden2/$', 'apps.pagos.views.preOrdenV2', name='preOrdenv2'),
    url(r'^pagar/$', 'apps.pagos.views.pagar', name='pagar'),
    url(r'^crearCuenta/$', 'apps.pagos.views.crearCuentaV2', name='crearCuentaV2'),
    url(r'^testTarjeta/$', 'apps.pagos.views.testTarjeta', name='testTarjeta'),

]

apps/servicios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

from apps.servicios.forms import PlatilloSearchForm
from apps.servicios.views import basic_search_nanoz

urlpatterns = [
    url(r'perfil-restaurante/(?P<slug>[\w-]+)/', 'apps.servicios.views.perfilRestaurante', name='perfilRestaurante'),
    url(r'mis-restaurantes/', 'apps.servicios.views.VistaRestaurante', name='verRestaurantes'),
    url(r'restaurante/(?P<slugRestaurante>[\w-]+)/platillo/(?P<slugPlatillo>[\w-]+)/$',
        'apps.servicios.views.detallePlatillo', name='detallePlatillo'),
    url(r'actualizar-platillo/', 'apps.servicios.views.ModificarPlatillo', name='actualizarPlatillo'),
    url(r'cancelar-pedido/', 'apps.servicios.views.cancelar_pedido', name='cancelarPedido'),
    url(r'actualizar-pedido/', 'apps.servicios.views.actualizar_pedido', name='actualizarPedido'),
    url(r'ajaxAgregarFavoritos/$', 'apps.servicios.views.ajaxAgregarFavoritos', name='ajaxAgregarFavoritos'),
    url(r'ajaxAgregarFavoritos2/$', 'apps.servicios.views.ajaxAgregarFavoritos2', name='ajaxAgregarFavoritos2'),
    url(r'ajax_agregar_platillo/$', 'apps.servicios.views.ajaxAgregarPlatillo', name='ajaxAgregarPlatillo'),
    url(r'ajax_quitar_platillo/$', 'apps.servicios.views.ajaxQuitarPlatillo', name='ajaxQuitarPlatillo'),
    url(r'ajax_quitar_1_platillo/$', 'apps.servicios.views.ajaxQuitar1Platillo', name='ajaxQuitar1Platillo'),
    # url(r'^search/', include('haystack.urls')),
    # url(r'^buscador/?$', MySearchView.as_view(), name="buscador"),
    # url(r'^buscador2/?$', buscador2, name="buscador2"),
    url(r'ajaxObtenerSemana/$', 'apps.servicios.views.ajaxObtenerSemana', name='ajaxObtenerSemana'),
    url(r'ajaxObtenerSemanaFacturas/$', 'apps.servicios.views.ajaxObtenerSemanaFacturas',
        name='ajaxObtenerSemanaFacturas'),
    url(r'ajaxObtenerExpecificacionSemana/$', 'apps.servicios.views.ajaxObtenerExpecificacionSemana',
        name='ajaxObtenerExpecificacionSemana'),
    url(r'^ordenar/?$', 'apps.servicios.views.search_with_form', name="buscador2"),
    url(r'^buscadorV2/?$', basic_search_nanoz, {
        'load_all': False,
        "form_class": PlatilloSearchForm,
    }, name="buscador"),

]

apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.usuarios.views.usuarioPerfil', name='usuarioPerfil'),
    url(r'login/$', 'apps.usuarios.views.LogIn', name='LogIn'),
    url(r'logout/$', 'apps.usuarios.views.LogOut', name='LogOut'),
    url(r'preguntas-frecuentes/$', 'apps.usuarios.views.faq', name='faq'),
    url(r'condiciones/$', 'apps.usuarios.views.condiciones', name='condiciones'),
    url(r'perfil/$', 'apps.servicios.views.PerfilUsuario', name='Perfil'),
    url(r'ajax_validar_correo/$', 'apps.usuarios.views.ajax_validar_correo', name='ajax_validar_correo'),
    url(r'ajax_actualizar_pedidos/$', 'apps.usuarios.views.ajax_actualizar_pedidos', name='ajax_actualizar_pedidos'),
    url(r'contacto/$', 'apps.usuarios.views.contactoRestaurante', name='Contacto'),
    url(r'mis-datos/$', 'apps.usuarios.views.datosExtra', name='datosExtra'),
    url(r'restaurante-datos/(?P<llave>\w+)/$', 'apps.usuarios.views.agregarRestaurante', name='addRestaurante'),
    url(r'restaurante/(?P<slug>[\w-]+)/$', 'apps.usuarios.views.detalleRestaurante', name='detalleRestaurante'),
    url(r'control-restaurantes/$', 'apps.usuarios.views.testGlovalV2', name='controlRestaurantes'),
    url(r'test/$', 'apps.usuarios.views.testGlovalV2', name='test'),
]

deliandgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [
    url(r'^$', 'apps.servicios.views.VistaPlatillos', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.estadisticas.urls', namespace='estadisticas_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.catalogos.urls', namespace='catalogos_app')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    # urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

templates/base/base.html
{% load staticfiles %}
{% load humanize %}
{% load replacePunto %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-STORE">
    <META HTTP-EQUIV="PRAGMA" CONTENT="NO-STORE">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    {% include 'base/favicons.html' %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">


    <script src="//maps.google.com/maps/api/js?key=AIzaSyC6UBtxDBeoxSoenu2vBIpgjcuRSk-O29Q"></script>
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script src="{% static 'base/js/jquery.mask.js' %}"></script>
    <script src="{% static 'base/js/jquery.validate.js' %}"></script>
    <script src="{% static 'base/js/localization/messages_es.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/spaces/spaces.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/spaces/spaces.bootstrap.min.css' %}">

    {% block styles %}

    {% endblock %}

</head>
<body>
<nav class="navbar navbar-default shadow">
    <div class="container-fluid">
        <div class="navbar-header visible-xs">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="{% url 'pagos_app:VerCarrito' %}" class="navbar-icon visible-xs right mt--xxs mr-xs"
               style="top: -4px; position: relative;">
                <i class="ion-bag"></i>
                <span class="badge ml--xs mt-xs hidden" style="background-color: #e91e63;">
                    {% total_carrito %}
                </span>
            </a>
            <a href="{% url "servicios_app:buscador2" %}" class="navbar-icon visible-xs right mt--xxs mr-s">
                <i class="ion-ios-search-strong" style="font-size: 1.8em !important;
                    position: relative;
                    top: -10px;"></i>
            </a>

            <a class="navbar-brand font-300" href="{% url "index" %}">
                <img src="https://image.flaticon.com/icons/png/512/172/172674.png" alt="logo"
                     style="height: 1em;
                    display: inline-block;
                    top: -2px;
                    position: relative;">
                Deli&Go
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav" style="z-index: 1; position: relative;">
                <li>
                    <a href="{% url "servicios_app:buscador2" %}" class="hidden-xs">
                        Ordenar
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="z-index: 1; position: relative;">
                <li>
                    <a href="{% url 'pagos_app:VerCarrito' %}" class="navbar-icon hidden-xs">
                        <i class="ion-bag"></i>
                        <span class="badge ml--xs mt-xs hidden" style="background-color: #e91e63;">
                            {% total_carrito %}
                        </span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <div class="avatar-usuario img-responsive">
                                <style>
                                    .avatar-usuario {
                                        background: url({{ user.urlImagen }});
                                        background-size: cover;
                                        background-position: center center;
                                        border-radius: 50%;
                                        height: 2em;
                                        width: 2em;
                                        float: left;
                                        top: -5px;
                                        position: relative;
                                        margin-right: 10px;
                                    }
                                </style>
                            </div>
                            &nbsp;<i class="ion-ios-arrow-down" style="top: 1px; position: relative;"></i>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="javascript:void(0);" class="mt-xxxs">¡Hola {{ user.get_short_name }}!</a></li>
                            <li class="divider"></li>
                            <li>
                                <a href="{% url 'usuarios_app:Perfil' %}">Mi perfil</a>
                            </li>
                            {% if user.is_restaurante %}
                                <li>
                                    <a href="{% url 'servicios_app:verRestaurantes' %}">Mis Restaurantes</a>
                                </li>
                            {% endif %}
                            <li class="divider"></li>
                            <li>
                                <a href="{% url 'usuarios_app:LogOut' %}">Salir</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'usuarios_app:LogIn' %}">Iniciar sesión</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-center hidden-xs">
                <li>
                    <a class="navbar-brand font-300" href="{% url "index" %}" style="width: 10em; margin: 0 auto;">
                        <img src="https://image.flaticon.com/icons/png/512/172/172674.png" alt="logo"
                             style="height: 1em;
                    display: inline-block;
                    top: -2px;
                    position: relative;">
                        Deli&Go
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-agregar-carrito">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            Se ha agregado al pedido
        </div>
    </div>
</div>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/cd941bc190.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>
<script src="{% static 'base/js/bootstrap-notify.min.js' %}"></script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
    window.$zopim || (function (d, s) {
        var z = $zopim = function (c) {
            z._.push(c)
        }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0];
        z.set = function (o) {
            z.set._.push(o)
        };
        z._ = [];
        z.set._ = [];
        $.async = !0;
        $.setAttribute("charset", "utf-8");
        $.src = "//v2.zopim.com/?4J4qwlMpOrvaeZLcMFBMO4T1xyDtHH84";
        z.t = +new Date;
        $.type = "text/javascript";
        e.parentNode.insertBefore($, e)
    })(document, "script");
    {% if user.is_authenticated %}
        $zopim(function () {
            $zopim.livechat.setName('{{ user.get_full_name }}');
            $zopim.livechat.setEmail('{{ user.email }}');
        });
    {% endif %}
</script>
<!--End of Zopim Live Chat Script-->
{% block scripts %}

{% endblock %}
</body>
</html>

templates/base/base_platillo_card.html
{% load static from staticfiles %}
{% load humanize %}

<style>

    .info-platillo {
        padding: 10px;
    }

    .info-platillo p {
        margin-bottom: 0;
    }

    .btn-add {
        line-height: 0;
        padding: 2px 15px;
        border: 1px solid #E0e0e0;
        color: #e91e63;
    }

    .btn-add i {
        font-size: 1.2em !important;
        color: #e91e63;
        -webkit-transition: all 0.3s ease;
        -moz-transition: all 0.3s ease;
        -ms-transition: all 0.3s ease;
        -o-transition: all 0.3s ease;
        transition: all 0.3s ease;
        filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        transform: rotate(90deg);
        display: inline-block;
    }

    .btn-add:hover i {
        filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2);
        -webkit-transform: rotate(180deg);
        -moz-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        -o-transform: rotate(180deg);
        transform: rotate(180deg);
        display: inline-block;
        color: #fff !important;
    }

    .btn-add:hover {
        background: #e91e63;
        border-color: #e91e63;
        color: #fff !important;
    }
</style>
<div class="p-0 div-platillo mb-s">
    <a href="{% url 'servicios_app:detallePlatillo' platillo.restaurante.slug platillo.slug %}">
        <div class="imagen-platillo border" id="imagen-platillo{{ platillo.id }}">
            <style>
                #imagen-platillo{{ platillo.id }} {
                    background: url({{ platillo.imagen.url }}) center center;
                    background-size: cover;
                    padding-bottom: 62.5%;
                }
            </style>
        </div>
    </a>
    <div class="info-platillo">
        <a href="{% url 'servicios_app:detallePlatillo' platillo.restaurante.slug platillo.slug %}">
            <h5 class="m-0 truncate">{{ platillo.nombre }}</h5>
        </a>
        <div class="row mt-xxxs">
            <div class="col-xs-6">
                <p class="text-primary font-600 left mt-xxxs">
                    <i class="ion-social-usd"></i>&nbsp;{{ platillo.precio|floatformat:'2' }}
                </p>
            </div>
            <div class="col-xs-6">
                <span class="no-shadow right pointer mt-xxxs btn-add animate"
                      onclick="ajaxAgregarPlatillo({{ platillo.id|floatformat:'0' }})">
                    <i class="ion-android-add"></i>
                </span>
            </div>
        </div>
    </div>
</div>

templates/base/favicons.html
{% load staticfiles %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'base/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'base/favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'base/favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'base/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'base/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'base/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'base/favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'base/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'base/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'base/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'base/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'base/favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">