apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.usuarios.views.usuarioPerfil', name='usuarioPerfil'),
    url(r'login/$', 'apps.usuarios.views.LogIn', name='LogIn'),
    url(r'logout/$', 'apps.usuarios.views.LogOut', name='LogOut'),
    url(r'preguntas-frecuentes/$', 'apps.usuarios.views.faq', name='faq'),
    url(r'condiciones/$', 'apps.usuarios.views.condiciones', name='condiciones'),
    url(r'perfil/$', 'apps.servicios.views.PerfilUsuario', name='Perfil'),
    url(r'ajax_validar_correo/$', 'apps.usuarios.views.ajax_validar_correo', name='ajax_validar_correo'),
    url(r'ajax_actualizar_pedidos/$', 'apps.usuarios.views.ajax_actualizar_pedidos', name='ajax_actualizar_pedidos'),
    url(r'contacto/$', 'apps.usuarios.views.contactoRestaurante', name='Contacto'),
    url(r'mis-datos/$', 'apps.usuarios.views.datosExtra', name='datosExtra'),
    url(r'restaurante-datos/(?P<llave>\w+)/$', 'apps.usuarios.views.agregarRestaurante', name='addRestaurante'),
    url(r'restaurante/(?P<slug>[\w-]+)/$', 'apps.usuarios.views.detalleRestaurante', name='detalleRestaurante'),
    url(r'control-restaurantes/$', 'apps.usuarios.views.testGlovalV2', name='controlRestaurantes'),
    url(r'test/$', 'apps.usuarios.views.testGlovalV2', name='test'),
]

deliandgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [
    url(r'^$', 'apps.servicios.views.VistaPlatillos', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.estadisticas.urls', namespace='estadisticas_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.catalogos.urls', namespace='catalogos_app')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    # urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/usuarios/models.py
# -*- encoding: utf-8 -*-
import os
import random
import string

from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.models import PermissionsMixin, BaseUserManager, AbstractBaseUser
from django.db import models
from django.db.models.aggregates import Avg
from django.templatetags.static import static
from django.utils.text import slugify
from geoposition.fields import GeopositionField

from apps.catalogos.models import Tags, CuentaBanco
from apps.usuarios.mailing import correo01


def directorio_img_restaurante(instance, filename):
    return "restaurante/{id}/{file}".format(id=instance.slug, file=filename)


def directorio_img_usuarios(instance, filename):
    return "usuarios/{id}/{file}".format(id=instance.id, file=filename)


class UserManager(BaseUserManager, models.Manager):
    def _create_user(self, username, email, password, is_staff,
                     is_superuser, is_active=False, **extra_fields):
        print("METODO _create_user")
        print(username, email, password)
        email = self.normalize_email(email)
        # if not email:
        # raise ValueError('El email debe ser obligatorio')
        user = self.model(username=email, email=email, is_active=is_active,
                          is_staff=is_staff, is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, is_active=True, **extra_fields):
        print("CREANDO USUARIO NORMAL")
        print(username, email, password)
        print(extra_fields)
        correo01(destino=[email, ])
        return self._create_user(username=email, email=email, password=password,
                                 is_staff=False, is_superuser=False, is_active=True, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        print("CREANDO SUPER USUARIO")
        print(username, email, password)
        print(extra_fields)
        return self._create_user(username=email, email=email, password=password,
                                 is_staff=True, is_superuser=True, is_active=True, **extra_fields)


class Usuario(AbstractBaseUser, PermissionsMixin):
    nombre = models.CharField(max_length=40, blank=True)
    apellidos = models.CharField(max_length=40, blank=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    avatar = models.FileField(blank=True, upload_to=directorio_img_usuarios)
    telefono = models.CharField(max_length=20, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_restaurante = models.BooleanField(default=False)
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    @property
    def get_short_name(self):
        if self.nombre != "":
            return self.nombre
        else:
            return self.email

    @property
    def get_full_name(self):
        if self.nombre != "":
            return self.nombre + " " + self.apellidos
        else:
            return str(self.email)

    @property
    def get_telefono(self):
        if self.telefono:
            return self.telefono
        else:
            return "0000000000"

    @property
    def urlImagen(self):
        if self.avatar:
            return self.avatar._get_url
        else:
            return static('base/img/default-avatar.jpg')

    @property
    def get_image_filename(self):
        return os.path.basename(self.imagen.name)

    @property
    def get_image_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            from django.contrib.staticfiles.templatetags.staticfiles import static
            return static('base/img/default_avatar.jpg')

    def __unicode__(self):
        return self.get_full_name

    def __str__(self):
        return self.get_full_name


class Contacto(models.Model):
    nombre_restaurante = models.CharField(max_length=200)
    nombre_responsable = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    email = models.EmailField(max_length=200)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    llaveRandom = models.CharField(max_length=20)
    direccion = GeopositionField()
    nombre_direccion = models.CharField(max_length=1000)
    url_yelp = models.CharField(max_length=1000, default="")
    estado = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nombre_restaurante + " " + self.nombre_responsable + " " + str(self.telefono)

    def __str__(self):
        return self.nombre_restaurante + " " + self.nombre_responsable + " " + str(self.telefono)

    def save(self, *args, **kwargs):
        if not self.id:
            self.llaveRandom = genera_codigo()
        super(Contacto, self).save(*args, **kwargs)


class Restaurante(models.Model):
    duenio = models.ForeignKey(Usuario)
    contacto = models.ForeignKey(Contacto)
    #tags = models.ManyToManyField(Tags)
    slug = models.SlugField(max_length=200)
    cuenta_bancaria = models.ForeignKey(CuentaBanco, null=True)
    compra_minima = models.IntegerField(default=0)
    # distancia maxima a la que el restaurante puede llevar pedidos
    alcanze = models.IntegerField(default=1.0)
    lista_servicio = (
        ("Solo Domicilio", "Solo Domicilio"),
        ("Solo Local", "Solo Local"),
        ("Domicilio y Local", "Domicilio y Local"),
    )
    servicio = models.CharField(choices=lista_servicio, max_length=20, default="Domicilio y Local")
    hora_abre = models.TimeField()
    hora_cierra = models.TimeField()
    imagen = models.FileField(upload_to=directorio_img_restaurante)
    costo_envio = models.IntegerField(default=0)
    RFC = models.CharField(max_length=13)

    def __str__(self):
        return str(self.contacto)

    def __unicode__(self):
        return str(self.contacto)

    @property
    def get_name(self):
        return self.contacto.nombre_restaurante

    @property
    def urlImagen(self):
        if self.imagen:
            return self.imagen._get_url
        else:
            return static('base/img/default-avatar.jpg')

    @property
    def comentarioAvg(self):
        cantidad = 0
        resultado = self.comentarios_set.all()
        if resultado.exists():
            cantidad = resultado.aggregate(Avg('valoracion'))['valoracion__avg']
        return cantidad

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.contacto.nombre_restaurante)
        super(Restaurante, self).save(*args, **kwargs)


class Direccion(models.Model):
    usuario = models.ForeignKey(Usuario)
    calle = models.TextField()
    numero_ext = models.IntegerField()
    numero_int = models.IntegerField()
    estado = models.CharField(max_length=50)
    CP = models.CharField(max_length=5, default='00000')
    referencia = models.TextField()
    fecha_hora = models.DateTimeField(auto_now_add=True)

    @property
    def get_full(self):
        return "Usuario:" + self.usuario.get_full_name + " Principal " + self.calle + " No. Ext." + str(
                self.numero_ext) + " C.P." + str(
                self.CP) + " Estado: " + self.estado + " referencia: " + self.referencia

    def __unicode__(self):
        return self.calle + "/" + str(self.numero_ext) + "/" + str(self.CP) + "/" + self.estado

    def __str__(self):
        return self.calle + "/" + str(self.numero_ext) + "/" + str(self.CP) + "/" + self.estado


def genera_codigo():
    codigo_prueba = cadena_aleatorio(20)
    while existe_codigo(codigo_prueba):
        codigo_prueba = cadena_aleatorio(20)
    return codigo_prueba


def cadena_aleatorio(tamanio):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(tamanio))


def existe_codigo(codigo):
    return Contacto.objects.filter(llaveRandom=codigo).exists()


class EmailOrUsernameModelBackend(ModelBackend):
    def authenticate(self, username=None, password=None):
        if '@' in username:
            kwargs = {'email': username}
        else:
            kwargs = {'username': username}
        try:
            user = Usuario.objects.get(**kwargs)
            if user.check_password(password):
                return user
        except Usuario.DoesNotExist as e:
            return None

    def get_user(self, username):
        try:
            return Usuario.objects.get(pk=username)
        except Usuario.DoesNotExist as e:

            return None

    def __str__(self):
        return str(self)

    @property
    def get_rating(self):
        return 0

templates/usuarios/DatosRestaurante.html
{% extends 'base/base.html' %}

{% load staticfiles %}

{% block title %}
    Información del Restaurante | Deli&Go
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'base/js/pickadate/themes/default.css' %}">
    <link rel="stylesheet" href="{% static 'base/js/pickadate/themes/default.time.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row section">
            <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
                <h3>Agrega la información del restaurante</h3>
                <form method="POST" enctype="multipart/form-data" id="form_restaurante">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                            {{ field.label_tag }}
                            {{ field }}
                            <p class="text-danger">{{ field.errors.as_text }}</p>
                        </div>
                    {% endfor %}
                    <button class="btn" type="submit">
                        Actualizar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'base/js/pickadate/picker.js' %}"></script>
    <script src="{% static 'base/js/pickadate/picker.time.js' %}"></script>
    <script src="{% static 'base/js/pickadate/translations/es_ES.js' %}"></script>
    <script>

        $('.timepicker').pickatime({
            formatSubmit: 'HH:i',
            hiddenName: true
        });

        $(document).ready(function () {
            $('#id_RFC').mask("LLLXNNNNNXXXX", {
                'translation': {
                    L: {pattern: /[A-Za-z]/},
                    N: {pattern: /[0-9]/},
                    X: {pattern: /[A-Za-z0-9]/}
                }
            });
        });
    </script>
{% endblock %}

templates/usuarios/login.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block title %}
    Regístrate | Inicia Sesión
{% endblock %}
{% block styles %}
    <style>
        body {
            background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url({% static 'base/img/bg-login.jpg' %}) center center;
            background-size: cover;
            background-attachment: fixed;
        }

        .container {
            min-height: 100vh;
        }

        .container > .row:first-child {
            margin-top: 64px;
        }

        .checkbox-recordar {
            display: inline-block;
            margin-top: 5px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="bg-login">
        <div class="container">
            <div class="row row-centered">
                <div class="col-xs-12 col-sm-7 col-md-6 col-lg-5 col-centered m-t-lg">
                    <div class="well white m-b-0 shadow">
                        <div class="tabs-container">
                            <ul class="nav nav-tabs row">
                                <li class="{% if not register_error %}active{% endif %} col-xs-6 text-center p-0">
                                    <a data-toggle="tab" href="#tab-login">¿Tienes cuenta?</a>
                                </li>
                                <li class="{% if register_error %}active{% endif %} col-xs-6 text-center p-0">
                                    <a data-toggle="tab" href="#tab-signup">¿Eres nuevo?</a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div id="tab-login"
                                     class="tab-pane {% if not register_error %}active{% endif %}">
                                    <div class="panel-body">
                                        <h3 class="m-t-sm font-800 text-center">Inicia sesión</h3>
                                        {% if error != '' %}
                                            <p class="text-danger">
                                                {{ error }}
                                            </p>
                                        {% endif %}
                                        <form class="m-t" role="form" method="post" accept-charset="utf-8"
                                              id="form_login">
                                            {% csrf_token %}

                                            <div class="form-group">
                                                <label for="id_username" class="control-label">
                                                    Correo electrónico:
                                                </label>
                                                <input id="id_username" maxlength="50" name="username"
                                                       class="form-control input-lg"
                                                       required type="text">
                                            </div>

                                            <div class="form-group">
                                                <label for="password"
                                                       class="control-label">Contraseña:</label>
                                                <input id="password" maxlength="50" name="password"
                                                       class="form-control input-lg"
                                                       required type="password">
                                            </div>

                                            <div class="form-group m-b-0">
                                                <div class="checkbox checkbox-recordar">
                                                    <label>
                                                        <input id="id_recordarme" name="recordarme"
                                                               type="checkbox">
                                                        Recordar mi cuenta
                                                    </label>
                                                </div>
                                                <button class="btn btn-primary btn-lg right" type="submit"
                                                        id="btn-login" name="login_form">
                                                    Inicia Sesión
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div id="tab-signup" class="tab-pane {% if register_error %}active{% endif %}">
                                    <div class="panel-body">
                                        <h3 class="m-t-sm font-800 text-center">Regístrate</h3>

                                        <form role="form" method="post" accept-charset="utf-8" id="form_signup">
                                            {% csrf_token %}

                                            {% for field in user_register %}

                                                <!-- Render the field label tag -->
                                                <div class="form-group {% if field.errors %}has-error{% endif %} ">
                                                    {{ field.label_tag }}
                                                    {{ field }}
                                                    <div class="error text-danger m-b-0">
                                                        {% if field.errors %}
                                                            {% for error in field.errors %}
                                                                <p class="text-danger m-b-0">
                                                                    {{ error|safe }}&nbsp;<i class="error"></i>
                                                                </p>
                                                            {% endfor %}
                                                        {% endif %}
                                                    </div>
                                                </div>

                                            {% endfor %}
                                            <div class="form-group">
                                                <label class="control-label" for="repass">Repite tu
                                                    contraseña:</label>
                                                <input id="repass" type="password" name="repass" required
                                                       class="form-control"/>
                                            </div>

                                            <div class="form-group m-b-0">
                                                <div class="checkbox checkbox-recordar">
                                                    <label>
                                                        <input type="checkbox" id="checkbox_terminos"
                                                               name="terminos">
                                                        <span>
                                                            Acepto los <br>
                                                            <a href="#" style="left: -8px; position: relative;">Términos y Condiciones</a>
                                                        </span>
                                                    </label>
                                                </div>
                                                <button class="btn btn-primary btn-lg right disabled m-t-sm"
                                                        id="btn-signup"
                                                        type="submit" disabled name="register_form">Regístrate
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'usuarios_app:Contacto' %}" class="text-white">
                        <div class="alert alert-success text-center m-b-0">
                            ¿Tienes un restaurante? <strong>Entra aquí</strong>
                        </div>
                    </a>
                </div>
            </div>
            <div class="row hidden">
                <div class="col-lg-6">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="EXVU8MZF9VS54">
                        <input type="image" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_subscribeCC_LG.gif"
                               border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
                        <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1"
                             height="1">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        var $tab_login = $('#tab-login');
        var $tab_signup = $('#tab-signup');

        $tab_login.find('form').validate({
            rules: {
                name: {
                    'required': true
                },
                username: {
                    required: true,
                    email: true
                }
            }
        });

        $tab_signup.find('form').validate({
            rules: {
                name: {
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                password: {
                    required: true,
                    minlength: 6
                },
                repass: {
                    equalTo: "#id_password"
                },
                terminos: {
                    required: true
                }
            }
        });

        $tab_login.find('form').submit(function () {
            if ($(this).valid()) {
                $('#btn-login').addClass('disabled').html('<i class="fa fa-circle-o-notch fa-spin fa-fw"></i>&nbsp;&nbsp;Iniciando...');
            }

        });
        $tab_signup.find('form').submit(function () {
            if ($(this).valid()) {
                $('#btn-signup').addClass('disabled').html('<i class="fa fa-circle-o-notch fa-spin fa-fw"></i>&nbsp;&nbsp;Registrando...');
            }
        });

        $('#checkbox_terminos').on('change', function () {
            if ($(this).is(':checked')) {
                $("#btn-signup").removeClass('disabled').attr('disabled', false);
            }
            else {
                $("#btn-signup").addClass('disabled').attr('disabled', true);
            }
            checkCorreoEnUso();
        });

        $(document).ready(function () {
            $('nav.navbar').addClass('navbar-inverse navbar-fixed-top navbar-transparent');
        });

        var $email = $("#id_email");
        $email.on('keyup', function () {
            checkCorreoEnUso();
        });
        $email.on('hover', function () {
            checkCorreoEnUso();
        });
        $email.on('change', function () {
            checkCorreoEnUso();
        });

        function checkCorreoEnUso() {
            var $this = $('#id_email');
            var correo = "" + $this.val();
            $.ajax({
                url: "{% url 'usuarios_app:ajax_validar_correo' %}",
                type: 'post',
                data: {"email": correo},
                beforeSend: function () {

                },
                success: function (data) {
                    if (data + "" == "True") {
                        $("#btn-signup").attr("disabled", true);
                        $this.closest('.form-group').addClass('has-error');
                        $this.next('div.error').html('El correo ya está en uso');
                        return true;
                    } else {
                        $("#btn-signup").attr("disabled", false);
                        $this.closest('.form-group').removeClass('has-error');
                        $this.next('div.error').html(null);
                        return false;
                    }
                },
                error: function (xhr, errmsg, err) {

                }
            });
        }
    </script>
{% endblock %}

templates/usuarios/otrosDatos.html
{% extends 'base/base.html' %}

{% load staticfiles %}

{% block title %}
    Completa tu registro | Deli&Go
{% endblock %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/file/fileinput.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <h3>
                    Sólo un paso más
                </h3>
                {{ error }}
                <form method="post" enctype="multipart/form-data">
                    {{ formset.management_form }}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'base/js/file/purify.min.js' %}"></script>
    <script src="{% static 'base/js/file/fileinput.min.js' %}"></script>
    <script src="{% static 'base/js/file/theme.js' %}"></script>
    <script src="{% static 'base/js/file/es.js' %}"></script>
    <script>
        $('.file').fileinput({
            theme: "fa",
            language: "es",
            showUpload: false,
        });
        $('#id_telefono').mask("(000)000-0000");
    </script>
{% endblock %}