apps/pagos/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    url(r'^carrito/$', 'apps.pagos.views.VerCarrito', name='VerCarrito'),
    # url(r'^preOrden/$', 'apps.pagos.views.preOrden', name='preOrden'),
    url(r'^preOrden2/$', 'apps.pagos.views.preOrdenV2', name='preOrdenv2'),
    url(r'^pagar/$', 'apps.pagos.views.pagar', name='pagar'),
    url(r'^crearCuenta/$', 'apps.pagos.views.crearCuentaV2', name='crearCuentaV2'),
    url(r'^testTarjeta/$', 'apps.pagos.views.testTarjeta', name='testTarjeta'),

]

apps/servicios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

from apps.servicios.forms import PlatilloSearchForm
from apps.servicios.views import basic_search_nanoz

urlpatterns = [
    url(r'perfil-restaurante/(?P<slug>[\w-]+)/', 'apps.servicios.views.perfilRestaurante', name='perfilRestaurante'),
    url(r'mis-restaurantes/', 'apps.servicios.views.VistaRestaurante', name='verRestaurantes'),
    url(r'restaurante/(?P<slugRestaurante>[\w-]+)/platillo/(?P<slugPlatillo>[\w-]+)/$',
        'apps.servicios.views.detallePlatillo', name='detallePlatillo'),
    url(r'actualizar-platillo/', 'apps.servicios.views.ModificarPlatillo', name='actualizarPlatillo'),
    url(r'cancelar-pedido/', 'apps.servicios.views.cancelar_pedido', name='cancelarPedido'),
    url(r'actualizar-pedido/', 'apps.servicios.views.actualizar_pedido', name='actualizarPedido'),
    url(r'ajaxAgregarFavoritos/$', 'apps.servicios.views.ajaxAgregarFavoritos', name='ajaxAgregarFavoritos'),
    url(r'ajaxAgregarFavoritos2/$', 'apps.servicios.views.ajaxAgregarFavoritos2', name='ajaxAgregarFavoritos2'),
    url(r'ajax_agregar_platillo/$', 'apps.servicios.views.ajaxAgregarPlatillo', name='ajaxAgregarPlatillo'),
    url(r'ajax_quitar_platillo/$', 'apps.servicios.views.ajaxQuitarPlatillo', name='ajaxQuitarPlatillo'),
    url(r'ajax_quitar_1_platillo/$', 'apps.servicios.views.ajaxQuitar1Platillo', name='ajaxQuitar1Platillo'),
    # url(r'^search/', include('haystack.urls')),
    # url(r'^buscador/?$', MySearchView.as_view(), name="buscador"),
    # url(r'^buscador2/?$', buscador2, name="buscador2"),
    url(r'ajaxObtenerSemana/$', 'apps.servicios.views.ajaxObtenerSemana', name='ajaxObtenerSemana'),
    url(r'ajaxObtenerSemanaFacturas/$', 'apps.servicios.views.ajaxObtenerSemanaFacturas',
        name='ajaxObtenerSemanaFacturas'),
    url(r'ajaxObtenerExpecificacionSemana/$', 'apps.servicios.views.ajaxObtenerExpecificacionSemana',
        name='ajaxObtenerExpecificacionSemana'),
    url(r'^ordenar/?$', 'apps.servicios.views.search_with_form', name="buscador2"),
    url(r'^buscadorV2/?$', basic_search_nanoz, {
        'load_all': False,
        "form_class": PlatilloSearchForm,
    }, name="buscador"),

]

apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.usuarios.views.usuarioPerfil', name='usuarioPerfil'),
    url(r'login/$', 'apps.usuarios.views.LogIn', name='LogIn'),
    url(r'logout/$', 'apps.usuarios.views.LogOut', name='LogOut'),
    url(r'preguntas-frecuentes/$', 'apps.usuarios.views.faq', name='faq'),
    url(r'condiciones/$', 'apps.usuarios.views.condiciones', name='condiciones'),
    url(r'perfil/$', 'apps.servicios.views.PerfilUsuario', name='Perfil'),
    url(r'ajax_validar_correo/$', 'apps.usuarios.views.ajax_validar_correo', name='ajax_validar_correo'),
    url(r'ajax_actualizar_pedidos/$', 'apps.usuarios.views.ajax_actualizar_pedidos', name='ajax_actualizar_pedidos'),
    url(r'contacto/$', 'apps.usuarios.views.contactoRestaurante', name='Contacto'),
    url(r'mis-datos/$', 'apps.usuarios.views.datosExtra', name='datosExtra'),
    url(r'restaurante-datos/(?P<llave>\w+)/$', 'apps.usuarios.views.agregarRestaurante', name='addRestaurante'),
    url(r'restaurante/(?P<slug>[\w-]+)/$', 'apps.usuarios.views.detalleRestaurante', name='detalleRestaurante'),
    url(r'control-restaurantes/$', 'apps.usuarios.views.testGlovalV2', name='controlRestaurantes'),
    url(r'test/$', 'apps.usuarios.views.testGlovalV2', name='test'),
]

deliandgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [
    url(r'^$', 'apps.servicios.views.VistaPlatillos', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.estadisticas.urls', namespace='estadisticas_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.catalogos.urls', namespace='catalogos_app')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    # urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/pagos/models.py
# -*- encoding: utf-8 -*-
from django.db import models

from apps.servicios.models import Pedido
from apps.usuarios.models import Usuario, Restaurante


class Tarjeta(models.Model):
    usuario = models.ForeignKey(Usuario, null=False)
    nombre = models.CharField(max_length=100)
    numero = models.CharField(max_length=20)
    numero_secreto = models.CharField(max_length=3)
    banco = models.CharField(max_length=20)
    # fecha expiracion
    mes = models.CharField(max_length=2)
    anio = models.CharField(max_length=4)
    fecha = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "tarjeta " + str(self.id) + " " + str(self.usuario.get_full_name)

    def __str__(self):
        return "tarjeta " + str(self.id) + " " + str(self.usuario.get_full_name)


class Pagos(models.Model):
    pedido = models.ForeignKey(Pedido)
    tarjeta = models.ForeignKey(Tarjeta)
    monto = models.FloatField(default=0.0)
    idConekta = models.CharField(max_length=1000)
    referencia = models.CharField(max_length=100)
    jsonPeticion = models.TextField()
    jsonRespuesta = models.TextField()
    codigo = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return self.pedido + " - " + self.tarjeta

    def __str__(self):
        return self.pedido + " - " + self.tarjeta


class Movimiento(models.Model):
    restaurante = models.ForeignKey(Restaurante)
    pedido = models.ForeignKey(Pedido, null=True)
    TIPO_MOVIMIENTOS = (
        ("venta", "venta"),
        ("deposito", "deposito"),
        ("multa", "multa"),
        ("comision", "comision"),
    )
    tipo = models.CharField(choices=TIPO_MOVIMIENTOS, max_length=10)
    monto = models.FloatField(default=0.0)
    fecha = models.DateField()

    def __unicode__(self):
        return str(self.restaurante) + " " + str(self.tipo) + " " + str(self.monto) + " " + str(self.fecha)

    def __str__(self):
        return str(self.restaurante) + " " + str(self.tipo) + " " + str(self.monto) + " " + str(self.fecha)

apps/pagos/views.py
# -*- encoding: utf-8 -*-
import datetime

import conekta
from django.conf import settings
from django.contrib.auth import login
from django.core.urlresolvers import reverse
from django.http.response import Http404
from django.shortcuts import render, redirect

from apps.pagos.forms import updateTarjetaForm, tarjetaForm, formDatosPedido
from apps.pagos.models import Tarjeta, Movimiento
from apps.servicios.models import Platillo, Pedido
from apps.usuarios.forms import updateDireccionForm, direccionForm, SignUpForm
from apps.usuarios.mailing import correo02, correo09
from apps.usuarios.models import Usuario, Direccion, EmailOrUsernameModelBackend


def VerCarrito(request):
    total = 0
    lista = []
    lista2 = []
    subTotalCarrito = 0
    costoEnvio = 0
    if request.method == "POST":
        carito = request.session["nanozcarrito"]
        for x in carito:
            print(carito[x])
            id_platillo = carito[x]["product_pk"]
            print(id_platillo)
            titulo = "cambios" + str(id_platillo)
            if titulo in request.POST:
                request.session[titulo] = request.POST[titulo]
            print(titulo)
            print(request.session[titulo])
        return redirect(reverse("pagos_app:preOrdenv2"))
    try:
        carito = request.session["nanozcarrito"]
        print(carito)
        print(type(carito))
        listaCambios = []
        for x in carito:
            print(carito[x])
            id_platillo = int(carito[x]["product_pk"])
            platillo = Platillo.objects.get(id=id_platillo)
            platillo.cantidad = int(carito[x]["quantity"])
            subTotal = platillo.cantidad * platillo.precio
            platillo.subTotal = subTotal
            titulo = "cambios" + str(id_platillo)
            if titulo in request.session:
                platillo.cambios = request.session[titulo]
            total += subTotal
            lista.append(platillo)
            subTotalCarrito += subTotal
        lista2 = sorted(lista, key=lambda platillo: platillo.id)
        costoEnvio = platillo.restaurante.costo_envio
        total += costoEnvio
    except Exception as e:
        print("error en el carrito")
        print(e.args)
    return render(request, "pagos/carrito.html", {
        "carrito": lista2,
        "total": total,
        "subTotalCarrito": subTotalCarrito,
        "constoEnvio": costoEnvio,
    })


'''
def preOrden(request):
    print("get")
    print(request.GET)
    print("post")
    print(request.POST)
    print("seccion")
    print(request.session)
    print("fin de los request")
    print("nanozcarrito" in request.session)
    if ("nanozcarrito" in request.session):
        carito = request.session["nanozcarrito"]
        for x in carito:
            print(carito[x])
            id_platillo = carito[x]["product_pk"]
            print(id_platillo)
            titulo = "cambios" + str(id_platillo)
            if titulo in request.POST:
                request.session[titulo] = request.POST[titulo]
            print(titulo)
            print(request.session[titulo])
    else:
        return redirect(reverse('index'))
    registrado = request.user.is_authenticated()
    data = {
        "user_register": SignUpForm(),
        "registrado": registrado,
    }
    if registrado:
        usuario = Usuario.objects.get(id=request.user.id)

        tarjetas = Tarjeta.objects.filter(
                usuario=usuario
        )

        for tarjeta in tarjetas:
            tarjeta.updateFormTar = updateTarjetaForm(
                    data={
                        "id_tarjeta": tarjeta.id,
                        "nombre": tarjeta.nombre,
                        "numero": tarjeta.numero,
                        "numero_secreto": tarjeta.numero_secreto,
                        "mes": tarjeta.mes,
                        "anio": tarjeta.anio,
                    }
            )
        data["tarjetas"] = tarjetas

        direcciones = Direccion.objects.filter(
                usuario=usuario
        )

        for direccion in direcciones:
            direccion.updateFormDir = updateDireccionForm(
                    data={
                        "id_direccion": direccion.id,
                        "calle": direccion.calle,
                        "numero_ext": direccion.numero_ext,
                        "numero_int": direccion.numero_int,
                        "estado": direccion.estado,
                        "CP": direccion.CP,
                        "referencia": direccion.referencia,
                    }
            )
        data["direcciones"] = direcciones
    if request.method == "POST":
        newTarjeta = tarjetaForm(request.POST)
        newDireccion = direccionForm(request.POST)
        updateTarjeta = updateTarjetaForm(request.POST)
        updateDireccion = updateDireccionForm(request.POST)
        if updateTarjeta.is_valid():
            try:
                actulizar_tarjeta(request)
                return redirect(reverse("pagos_app:preOrden"))
            except Exception as e:
                print(e.args)
        else:
            if newTarjeta.is_valid():
                crear_tarjeta(request)
                return redirect(reverse("pagos_app:preOrden"))
            else:
                print("error creando nueva tarjeta")
                print(str(newTarjeta.errors))
        if updateDireccion.is_valid():
            try:
                actualizar_tarjeta(request)
                return redirect(reverse("pagos_app:preOrden"))
            except Exception as e:
                print(e.args)
        else:
            if newDireccion.is_valid():
                crear_direccion(request)
                return redirect(reverse("pagos_app:preOrden"))
            else:
                print("error creando nueva direccion")
                print(str(newDireccion.errors))

    newTarjeta = tarjetaForm()
    newDireccion = direccionForm()
    if "errorTarjeta" in request.session:
        data["error"] = request.session["errorTarjeta"]
        del request.session["errorTarjeta"]
    data["newTarjeta"] = newTarjeta
    data["newDireccion"] = newDireccion
    data["conektaLlavePublica"] = settings.CONEKTA_PUBLIC
    return render(request, "pagos/preOrden.html", data)
'''
'''
def pagar(request):
    print("get")
    print(request.GET)
    print("post")
    print(request.POST)
    print("seccion")
    print(request.session)
    print("fin de los request")
    print("nanozcarrito" in request.session)
    error = []
    if "nanozcarrito" in request.session and request.method == "POST":
        platillos, costoEnvio, total, detalles, visible = obtener_carrito(request)
        if "pedidoId" in request.session:
            print("se encontro el pedido en seccion")
            print(request.session["pedidoId"])
            pedido = Pedido.objects.get(llave=request.session["pedidoId"])
            print(pedido.id)
        else:
            print("no se encontro el pedido en seccion se creara uno nuevo")
            pedido = Pedido.objects.create(
                    monto_total=total + costoEnvio,
                    estado="en cargo",
                    nombre_recibe=request.POST["nombre_recibe"],
                    detalles=detalles
            )
            request.session["pedidoId"] = pedido.llave
        pedido.platillo = platillos
        pedido.save()
        if request.user.is_authenticated():
            print("usuario autentificado")
            if "id_tarjeta_select" in request.POST and "id_direccion_select" in request.POST:
                # if "id_direccion_select" in request.POST:
                direccion = Direccion.objects.get(id=request.POST["id_direccion_select"])
                print(type(direccion))
                print(vars(direccion))
                if "conektaTokenId" in request.POST:
                    try:
                        conekta.api_key = settings.CONEKTA_PRIVATE
                        conekta.locale = "es"
                        usuario = Usuario.objects.get(id=request.user.id)
                        lista_de_platillos = []
                        pedido.direccion = direccion.get_full
                        pedido.usuario = usuario.id
                        pedido.save()
                        for platillo in pedido.platillo.all():
                            print(platillo)
                            dicionario = {
                                "name": platillo.nombre,
                                "description": platillo.descripcion,
                                "unit_price": platillo.precio * 100,
                                "quantity": 1,
                                "type": "comida"
                            }
                            lista_de_platillos.append(dicionario)
                        charge = conekta.Charge.create({
                            "description": "Comida a domicilio",
                            "amount": pedido.monto_total * 100,
                            "currency": "MXN",
                            "reference_id": pedido.llave,
                            "card": request.POST["conektaTokenId"],
                            "details": {
                                "name": usuario.get_full_name,
                                "phone": usuario.get_telefono,
                                "email": usuario.email,
                                "line_items": lista_de_platillos,
                                "billing_address": {
                                    "street1": direccion.calle,
                                    "street2": direccion.numero_ext,
                                    "street3": direccion.numero_int,
                                    "city": "DistritoFederal",
                                    "state": direccion.estado,
                                    "zip": direccion.CP,
                                    "country": "Mexico",
                                    "phone": usuario.get_full_name,

templates/pagos/carrito.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}
    Carrito | Deli&Go
{% endblock %}

{% block styles %}
    <style>
        .icon-add, .icon-remove {
            line-height: 1.3;
            font-size: 1.5em;
        }
    </style>
{% endblock %}

{% block content %}
    {% if carrito|length == 0 %}
        <div class="container">
            <div class="row section">
                <div class="col-xs-12">
                    <h5>
                        Lo sentimos su pedido esta vacio
                    </h5>
                    <a class="btn btn-danger btn-lg" href="{% url 'index' %}">
                        Ver Platillos
                    </a>
                </div>
            </div>
        </div>
    {% else %}
        <form method="post">
            <div class="container">
                <div class="row section">
                    <div class="col-xs-12">
                        <h3 class="font-800">Resumen de tu pedido</h3>
                    </div>
                    <div class="col-xs-12 col-md-9">
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th></th>
                                    <th>Nombre</th>
                                    <th class="text-center">Cantidad</th>
                                    <th class="text-right">Precio</th>
                                    <th class="text-right">Subtotal</th>
                                    <th colspan="2"></th>
                                </tr>

                                {% csrf_token %}
                                {% for item in carrito %}
                                    <tr>
                                        <td>
                                            <div class="avatar" id="img-item{{ item.id }}">
                                                <style>
                                                    #img-item{{ item.id }} {
                                                        background: url({{ item.imagen.url }}) center center;
                                                        background-size: cover;
                                                        width: 70px;
                                                        height: 70px;
                                                    }
                                                </style>
                                            </div>
                                        </td>
                                        <td>{{ item.nombre }}</td>
                                        <td class="text-center">
                                        <span class="pointer"
                                              onclick="ajaxQuitar1Platillo({{ item.id|floatformat:'0' }})">
                                            <i class="material-icons icon-remove">remove</i>
                                        </span>
                                            {{ item.cantidad }}
                                            <span class="pointer"
                                                  onclick="ajaxAgregarPlatillo({{ item.id|floatformat:'0' }})">
                                            <i class="material-icons icon-add">add</i>
                                        </span>
                                        </td>
                                        <td class="text-right">${{ item.precio|floatformat:2|intcomma }}</td>
                                        <td class="text-right">${{ item.subTotal|floatformat:2|intcomma }}</td>
                                        <td>
                                            <div class="form-group">
                                                <input class="form-control mt-xs" type="text"
                                                       name="cambios{{ item.id }}"
                                                       id="cambios{{ item.id }}"
                                                       value="{{ item.cambios }}" placeholder="Observaciones">
                                            </div>
                                        </td>
                                        <td>
                                            <h4 class="pointer no-margins"
                                                onclick="ajaxQuitarPlatillo({{ item.id|floatformat:'0' }})">
                                                <i class="material-icons text-danger">clear</i>
                                            </h4>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-3">
                        <div class="well">

                            <p class="m-0">Subtotal: <b class="right">${{ subTotalCarrito|floatformat:"2" }}</b></p>
                            <p class="m-0">Costo envio: <span class="right">+ {{ constoEnvio|floatformat:"2" }}</span>
                            </p>
                            <h5>Total: <b class="right">${{ total|floatformat:"2" }}</b></h5>
                            <button type="submit" class="btn btn-danger btn-block btn-lg mt-xs">
                                Continuar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    {% endif %}

{% endblock %}

{% block scripts %}
    <script>
        function ajaxQuitarPlatillo(id_platillo) {
            $.ajax({
                url: "{% url 'servicios_app:ajaxQuitarPlatillo' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {

                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, errmsg, err) {
                    alert("No se pudo quitar el platillo");
                }
            });
        }
        function ajaxQuitar1Platillo(id_platillo) {
            $.ajax({
                url: "{% url 'servicios_app:ajaxQuitar1Platillo' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {

                },
                success: function (data) {
                    {% comment %}
                    console.log(data);
                    console.log(data["costoEnvio"]);
                    console.log(data["total"]);
                    for (var i = 0; i < data["platillos"].length; i++) {
                        console.log(data["platillos"][i]["id"]);
                        console.log(data["platillos"][i]["nombre"]);
                        console.log(data["platillos"][i]["subtotal"]);
                        console.log(data["platillos"][i]["cantidad"]);
                        console.log(data["platillos"][i]["precio"]);
                    }
                    {% endcomment %}
                    location.reload();
                },
                error: function (xhr, errmsg, err) {
                    alert("no se pudo quitar el platillo");
                }
            });
        }
        function ajaxAgregarPlatillo(id_platillo) {
            console.log(id_platillo);
            $.ajax({
                url: "{% url 'servicios_app:ajaxAgregarPlatillo' %}",
                type: 'post',
                data: {"id_platillo": id_platillo},
                beforeSend: function (xhr) {
                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, errmsg, err) {
                    alert("no se pudo quitar el platillo");
                }
            });
        }
    </script>
{% endblock %}

templates/pagos/pagar.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
    Gracias | Deli&Go
{% endblock %}
{% block styles %}
    <style>

        .form-group, .input-group {
            margin-bottom: 5px;
        }

        #id_password_signin {
            width: 100%;
            z-index: 10;
        }

        .nav.nav-tabs li {
            width: 50%;
            color: #009688 !important;
        }

        .top-navigation .nav > li.active {
            background: none;
        }

        .nav.nav-tabs li a {
            color: #444DFF !important;
            text-decoration: underline;
        }

        .nav.nav-tabs li.active a {
            color: #000 !important;
            text-decoration: none;
        }

        .wrapper .middle-box {
            margin-top: 0;
            margin-bottom: 40px;
        }

        .psw {
            position: relative;
            width: 100%;
            z-index: 10;
            background: transparent;
            height: 34px;
            -webkit-transition: border .25s linear, color .25s linear;
            -moz-transition: border .25s linear, color .25s linear;
            -o-transition: border .25s linear, color .25s linear;
            transition: border .25s linear, color .25s linear;
            -webkit-backface-visibility: hidden;
            width: 100%;
        }

        .psw:focus {
            outline: 0;
        }

        .strength_meter {
            background: #fff;
            position: absolute;
            left: 0px;
            top: 0px;
            width: 85%;
            height: 34px;
            z-index: 0;
            border-radius: 5px;
            padding-right: 13px;
        }

        .button_strength {
            text-decoration: none;
            font-size: 12px;
        }

        .strength_meter div {
            width: 0%;
            height: 34px;
            text-align: right;
            color: #000;
            line-height: 34px;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            -o-transition: all .3s ease-in-out;
            -ms-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
            padding-right: 12px;
            border-radius: 5px;
        }

        .strength_meter div p {
            position: absolute;
            top: 22px;
            right: 0px;
            color: #FFF;
            font-size: 13px;
        }

        .veryweak {
            background-color: #EF5350;
            border-color: #EF5350 !important;
            width: 25% !important;
            opacity: 0.4;
        }

        .weak {
            background-color: #FF9800;
            border-color: #FF9800 !important;
            width: 50% !important;
            opacity: 0.4;
        }

        .medium {
            background-color: #1DE9B6;
            border-color: #1DE9B6 !important;
            width: 75% !important;
            opacity: 0.4;
        }

        .strong {
            background-color: #536DFE;
            border-color: #536DFE !important;
            width: 100% !important;
            opacity: 0.4;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1>Gracias por su compra</h1>

        </div>
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
            {% if user.is_anonymous %}
                <h1>Tu pedido esta en camino checa tu correo para mas informacion</h1>
            {% else %}
                <h1>Ve a tu perfil para ver el estado de tu pedido</h1>
                <a href="{% url 'usuarios_app:Perfil' %}">
                    <span class="btn">
                        Ir a mi perfil
                    </span>
                </a>
            {% endif %}
        </div>
    </div>

{% endblock %}


{% block scripts %}
{% endblock %}